web/router.ex
defmodule RnlHackathon.Router do
  use RnlHackathon.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RnlHackathon do
    pipe_through :browser # Use the default browser stack

    get "/", IdeaController, :index

    put "/ideas/:idea_id/complete", IdeaController, :mark_complete
    put "/ideas/:idea_id/archive", IdeaController, :archive
    put "/ideas/:idea_id/unarchive", IdeaController, :unarchive
    get "/ideas/completed", IdeaController, :completed_index
    get "/ideas/archived", IdeaController, :archived_index
    resources "/ideas", IdeaController do
      resources "/interests", InterestController, only: [:create, :delete]
    end

    # For Passport
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/signup", RegistrationController, :new
    post "/signup", RegistrationController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", RnlHackathon do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule RnlHackathon.LayoutView do
  use RnlHackathon.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>STORABLE Hackathon</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if logged_in?(@conn) do %>
            <%= tag :meta, name: "user_token", content: Phoenix.Token.sign(@conn, "user_id", current_user(@conn).id) %>
              <li>
                <a href=""><%= current_user(@conn).name %></a>
              </li>
              <li><a href="<%= session_path(@conn, :delete) %>">Logout</a></li>
            <% else %>
              <li><a href="<%= session_path(@conn, :new) %>">Login</a></li>
              <li><a href="<%= registration_path(@conn, :new) %>">Register</a></li>
            <% end %>
          </ul>
        </nav>
        <a href="/"><h1>STORABLE Hackathon</span></a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>